### ISSUE TITLE
Python 2.7 Support

### ISSUE THREAD

**Issue by pjdufour** [OCHA-DAP/hdx-python-api#1]
I'd suggest adding python 2.7 support to enable use of this code by the wider humanitarian community.

It would be great to have `1 click` publishing of datasets to HDX from GeoNode systems (http://geonode.org/), which contain many datasets potentially useful on HDX.  For instance, a popup that appears asking if you would like to publish to HDX.

GeoNode is currently written in Python 2.7 (https://github.com/geonode/geonode).  GeoNode (as well as other systems) can only be upgraded to Python 3.0 once all their dependencies are upgraded, which could still be years away.

A standard python API that shields the complexity of CKAN's REST API is great!  However, to seamlessly integrate HDX publishing into workflows, the code will need to run directly within business systems rather than as a separate script.

**Comment by mcarans** [comment]
Thank you for this suggestion. I need to investigate how difficult this will be eg. if any dependencies are Python 3 only, type hinting on Python 2.

I found this: http://python-future.org/quickstart.html which may help.

**Comment by mcarans** [comment]
As expected, the biggest problem are the Python 3.5 type hints, but there is a solution: [](https://www.python.org/dev/peps/pep-0484/#suggested-syntax-for-python-2-7-and-straddling-code)

**Comment by mcarans** [comment]
2 developments would simplify the exercise of changing the type hints significantly:
1. [PyCharm type hint conversion](https://youtrack.jetbrains.com/issue/PY-21251)
2. [pasteurize convert Py3.5 func annotations to Py2.7/3.5 instead of deleting](https://github.com/PythonCharmers/python-future/issues/258)

**Comment by tim6her** [comment]
Are you looking for collaborators to achieve Python 2.7 compatibilty? I could help but if your plan is to implement further features that might break the API, I'd rather not start yet.

**Comment by mcarans** [comment]
Hi @tim6her. Thanks for your interest in collaborating to make this library Python 2.7 compatible. I think the API should be relatively stable now. Please let me know if you need further information from me.

I would like to retain the type hints by converting them to a format compatible with Python 2.7 rather than stripping them out. I think this is the correct way to do it and it is what PyCharm supports:
[https://www.python.org/dev/peps/pep-0484/#suggested-syntax-for-python-2-7-and-straddling-code](https://www.python.org/dev/peps/pep-0484/#suggested-syntax-for-python-2-7-and-straddling-code)

**Comment by bdon** [comment]
I'm also interested in helping add Python 2.7 support. 👍

**Comment by mcarans** [comment]
@bdon Thanks for volunteering. @tim6her, @bdon I have added you both as collaborators. Thinking of where to start with this, unless you have some other suggestions, I think it is with the type hints as they will break 2.7 in their current form. They can be changed to the new form without breaking anything.

As for how to organise, my preference would be pull requests.

**Comment by tim6her** [comment]
Please don't mind me asking. I am fairly new to type hints. Are you using [mypy](http://mypy.readthedocs.io/en/latest/index.html)?

I have started rewriting the type hints and would like to compare them to the old ones with the output of some type checker. However, mypy spits out a lot of complaints using its standard settings on your code and mine. Which ones do you ignore?

Could you send me your test script for the static type check?

**Comment by mcarans** [comment]
Hi @tim6her . I have not been using mypy just the built in support for type hints in PyCharm. Your idea of using mypy to check output before and after sounds like a good one to me.

I guess the tests in the project under the tests/hdx folder are probably the best scripts available for the static type check. In PyCharm if you give the wrong types eg. by changing one of the tests, then it will complain. 

I am not familiar with using mypy, so if you are able to find a way to use it for this, then please elaborate in a comment here. What sort of complaints is mypy giving?

**Comment by tim6her** [comment]
Hi @mcarans ,

I did dump the output of `$ mypy hdx/configuration.py --ignore-missing-import` into a [Gist][gist1].  (`--ignore-missing-import` is necessary because of missing stub files)

Revision 1 shows the output of commit [b5c8f21][b5c8f21], which corresponds to your last edit, while revision 2 shows the output after my modifications ([db7a681][db7a681]). Doing the same for *hdx/data/dataset.py* yields [this.](gist2)

From what I can see, both outputs coincide up to line numbers and *mypy* only complains because dynamic and static typing is mixed. I think the best way forward is to keep reformatting the type hints and run a comparison of the *mypy*-outputs afterwards. I was just hoping that you had a solution for avoiding this strict type checking behaviour of *mypy* at hand.

[gist1]: https://gist.github.com/tim6her/6ba0bf48feb337e69bd411afc41f7380/revisions
[gist2]: https://gist.github.com/tim6her/ce9962029810050a7a74a8b06c988832/revisions
[b5c8f21]: https://github.com/tim6her/hdx-python-api/commit/b5c8f21ea001fa0673f201d9033694555467d7a2
[db7a681]: https://github.com/tim6her/hdx-python-api/tree/db7a681108d8e0687097c29a9f00ed2d6c997165

**Comment by bdon** [comment]
notes on getting tests running on python 2.7:

* syntax: remove type annotations
* syntax: remove `from e` in `except` blocks
* standard library: urllib.parse and UserDict moved, use `six.moves` package
* standard library: no `FileNotFound` exception class, define it yourself
* standard library: `Configuration`, `HDXObject` inherit from `object` to become new-style classes (this is default in python 3)
* import semantics: module named `logging` clashes with standard library, rename `hdx.logging` to `hdx.hdx_logging` 

perhaps:
* type annotations moved into __annotations__ attribute on function object

**Comment by bdon** [comment]
https://github.com/OCHA-DAP/hdx-python-api/blob/master/hdx/utilities/dictandlist.py#L26 has some redundant conditions; str won't work for python 2 as the type will be `unicode`: use `six.text_type` instead

https://github.com/OCHA-DAP/hdx-python-api/blob/master/hdx/data/dataset.py#L510 `range()` here with `sys.maxsize` will crash python 2: use `xrange()` or reevaluate if we really need `sys.maxsize` here

**Comment by bdon** [comment]
regarding https://github.com/OCHA-DAP/hdx-python-api/blob/master/hdx/utilities/dictandlist.py#L26. - python 2 version may need both 'str' and 'unicode' checks depending on where the original string came from - literal, loaded via json, etc

https://github.com/OCHA-DAP/hdx-python-api/blob/master/hdx/facades/scraperwiki.py#L7 the `import scraperwiki` line is also a naming conflict on python 2 so rename perhaps to `hdx_scraperwiki.py`

**Comment by bdon** [comment]
https://github.com/OCHA-DAP/hdx-python-api/blob/master/hdx/utilities/dictandlist.py#L156 `itertools.zip_longest` does not exist in python 2

**Comment by mcarans** [comment]
Thanks to both of you @tim6her and @bdon for your feedback so far

@bdon Regarding type annotations, I think this from PEP 484 is the right way to do it:
 (https://www.python.org/dev/peps/pep-0484/#suggested-syntax-for-python-2-7-and-straddling-code) as this will allow the annotations to work with IDEs which helps people using the library.

**Comment by bdon** [comment]
PR #2 should interact minimally with @tim6her 's changes to type annotations, only conflict would be the file rename of `logging` and `scraperwiki`.

**Comment by tim6her** [comment]
I have just created PR #3 including the changes of PR #2 by @bdon and the reformatted type hints according to PEP 484. The build is passing on travis-ci using Python 2.7. Should I include the changes to '.travis.yml' in the pull request?

**Comment by mcarans** [comment]
Thanks so much to @tim6her and @bdon for making this happen!
